### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by treysis** [ivanmeler/SamFirm_Reborn#1]
```
Checking firmware for SM-G935F/DBT/G935FXXS3ERJ2/G935FDBT3ERG2/G935FXXU3ERHC/G935FXXS3ERJ2
Error: Could not send BinaryInform. Status code 200/401
    Authorization failed
Could not fetch info for SM-G935F/DBT. Please verify the input or use manual info
```

**Comment by corsicanu** [comment]
No issue here tho, are you sure you're not forcing manual and/or too old build numbers?

![image](https://user-images.githubusercontent.com/6254131/115152830-80f69f80-a07b-11eb-9d6b-5b7a050a4ebf.png)

**Comment by treysis** [comment]
Embarrassing....I opened the old SamFirm.exe ^^
