### ISSUE TITLE
403

### ISSUE THREAD

**Issue by linux-rm** [ivanmeler/SamFirm_Reborn#10]
> #7 
>
> Date: 04-10-2023
>
> I've been waiting for two weeks. But there are still problems.

log:

SamFirm v0.5.0
Checking firmware for SM-G9910/CHC/G9910ZCU5EWH6/G9910CHC5EWH6/G9910ZCU5EWH6/G9910ZCU5EWH6
Model: SM-G9910
Version: G9910ZCU5EWH6/G9910CHC5EWH6/G9910ZCU5EWH6/G9910ZCU5EWH6
OS: T(Android 13)
Filename: SM-G9910_3_20230814150110_knpwbph4bk_fac.zip.enc4
Size: 8922489280 bytes
LogicValue: 31iobgihl6misgjy

Filename: C:\Users\linux-rm\Desktop\tar\SM-G9910_3_20230814150110_knpwbph4bk_fac.zip.enc4
Trying to download SM-G9910_3_20230814150110_knpwbph4bk_fac.zip.enc4 to C:\Users\linux-rm\Desktop\tar\SM-G9910_3_20230814150110_knpwbph4bk_fac.zip.enc4
Error getting response: 远程服务器返回错误: (__403__) 已禁止。
__`Error downloading: 403`__
Download finished

Checking CRC32...
File for crc check not found
System.IO.FileNotFoundException: File for crc check not found
   在 SamFirm.Utility.CRCCheck(String file, Byte[] crc) 位置 C:\Users\Ivan\Desktop\samfirm\Utility.cs:行号 94
   在 SamFirm.Form1.<download_button_Click>b__43_0(Object o, DoWorkEventArgs _e) 位置 C:\Users\Ivan\Desktop\samfirm\Form1.cs:行号 206

> And there is also code 403 in [Frija](https://github.com/SlackingVeteran/frija).

**Comment by griha41** [comment]
应用程序开发人员已意识到此问题。
很难说这种情况什么时候能得到解决，我希望很快就会发生。

为了尽可能简化，该错误是由于三星放弃了对协议版本1的支持并完全切换到版本2而导致的。开发人员正在尝试解决这个问题，这将允许访问新的固件区域程序的版本。

**Comment by griha41** [comment]
> > #7
> > Date: 04-10-2023
> > I've been waiting for two weeks. But there are still problems.
> 
> log:
> 
> SamFirm v0.5.0 Checking firmware for SM-G9910/CHC/G9910ZCU5EWH6/G9910CHC5EWH6/G9910ZCU5EWH6/G9910ZCU5EWH6 Model: SM-G9910 Version: G9910ZCU5EWH6/G9910CHC5EWH6/G9910ZCU5EWH6/G9910ZCU5EWH6 OS: T(Android 13) Filename: SM-G9910_3_20230814150110_knpwbph4bk_fac.zip.enc4 Size: 8922489280 bytes LogicValue: 31iobgihl6misgjy
> 
> Filename: C:\Users\linux-rm\Desktop\tar\SM-G9910_3_20230814150110_knpwbph4bk_fac.zip.enc4 Trying to download SM-G9910_3_20230814150110_knpwbph4bk_fac.zip.enc4 to C:\Users\linux-rm\Desktop\tar\SM-G9910_3_20230814150110_knpwbph4bk_fac.zip.enc4 Error getting response: 远程服务器返回错误: (**403**) 已禁止。 **`Error downloading: 403`** Download finished
> 
> Checking CRC32... File for crc check not found System.IO.FileNotFoundException: File for crc check not found 在 SamFirm.Utility.CRCCheck(String file, Byte[] crc) 位置 C:\Users\Ivan\Desktop\samfirm\Utility.cs:行号 94 在 SamFirm.Form1.<download_button_Click>b__43_0(Object o, DoWorkEventArgs _e) 位置 C:\Users\Ivan\Desktop\samfirm\Form1.cs:行号 206
> 
> > And there is also code 403 in [Frija](https://github.com/SlackingVeteran/frija).

再会。 该应用程序的测试版已在开发者页面 [0.3.6.5](https://github.com/ivanmeler/SamFirm_Reborn/releases/tag/0.3.6.5) 上发布。 您可以尝试使用 Microsoft Visual Studio 2019 或 2022 构建它。
我刚刚自己组装并测试了我的三星的下载。 一切顺利！

**Comment by ivanmeler** [comment]
New release is up with this issue resolved, thanks for bringing it into attention
