### ISSUE TITLE
(401) Unauthorized occurred during download

### ISSUE THREAD

**Issue by 869570967** [ivanmeler/SamFirm_Reborn#11]
![企业微信截图_16980261222497](https://github.com/ivanmeler/SamFirm_Reborn/assets/59461158/60c7e34c-9c44-4e52-b946-889eb620f54f)

**Comment by MdHusainhfz** [comment]
Same problem, I didn't pause the download; suddenly connection interrupted & error.

`Filename: D:\driverPKG\SM-A600FN_2_20220226092401_5w7ep7of4j_fac.zip.enc4`
`Trying to download SM-A600FN_2_20220226092401_5w7ep7of4j_fac.zip.enc4 to D:\driverPKG\SM-A600FN_2_20220226092401_5w7ep7of4j_fac.zip.enc4`
`Error: Connection interrupted`
`Download paused`
`Reconnecting...`
`Trying to download SM-A600FN_2_20220226092401_5w7ep7of4j_fac.zip.enc4 to D:\driverPKG\SM-A600FN_2_20220226092401_5w7ep7of4j_fac.zip.enc4`
`Error getting response: The remote server returned an error: (401) Unauthorized.`
`Error: Could not send BinaryInform. Status code 401/0`
`    Authorization failed`
`Download finished`
` `
`Checking CRC32...`
`Error: CRC does not match. Please redownload the file.`
@ivanmeler

**Comment by corsicanu** [comment]
Randomly samsung servers are kicking connection, security related. Wait few hours and try again, or try other network or ISP entirely if the problem persists.

**Comment by ivanmeler** [comment]
Latest release resolves that issue, get it from
https://github.com/ivanmeler/SamFirm_Reborn/releases/tag/0.3.6.6
