### ISSUE TITLE
Dysfonctionnement since last windows update

### ISSUE THREAD

**Issue by BabassXsama** [ivanmeler/SamFirm_Reborn#12]
Hi,
i can't use your app since the KB5031905 was installed. 
[SamFirm.log](https://github.com/ivanmeler/SamFirm_Reborn/files/13257178/SamFirm.log)

**Comment by corsicanu** [comment]
Download and install Visual-C-Runtimes-All-in-One from [here](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/) then redownload latest release from [here](https://github.com/ivanmeler/SamFirm_Reborn/releases/latest).

**Comment by ivanmeler** [comment]
Latest release resolves that issue, get it from
https://github.com/ivanmeler/SamFirm_Reborn/releases/tag/0.3.6.6

**Comment by BabassXsama** [comment]
Thank for all.

De : Ivan Meler ***@***.***>
Envoyé : lundi 11 décembre 2023 10:30
À : ivanmeler/SamFirm_Reborn ***@***.***>
Cc : BabassXsama ***@***.***>; Author ***@***.***>
Objet : Re: [ivanmeler/SamFirm_Reborn] Dysfonctionnement since last windows update (Issue #12)

Latest release resolves that issue, get it from
https://github.com/ivanmeler/SamFirm_Reborn/releases/tag/0.3.6.6
