### ISSUE TITLE
0.3.6.6 detected as trojan by Windows defender

### ISSUE THREAD

**Issue by QuentinSc** [ivanmeler/SamFirm_Reborn#13]
Hello,

When downloading the last release, 0.3.6.6, Widonws Defender flagged it as "Trojan:Win32/Wacatac.B!ml".
It is not the cas with the previous release.

**Comment by ivanmeler** [comment]
False positive, windows defender sometimes does it with compressed files, project is also fully open sourced so you can compile it yourself, funny enough this did happen to me with previous release but disappeared after few days
