### ISSUE TITLE
 Can I download the specified version?

### ISSUE THREAD

**Issue by xujimian** [ivanmeler/SamFirm_Reborn#14]
Can I download the specified version? Or should I only be able to download the latest version?

**Comment by ivanmeler** [comment]
Latest, samsung usually only keeps latest release on their server and this tool downloads directly from their servers.
In some cases they do keep older release available and you can download it by using manual method.

Good alternative for getting older firmwares is samfw.com which has a lot of them archived and gives you full download speed

**Comment by xujimian** [comment]
Okay, thank you
