### ISSUE TITLE
Not working for Galaxy S2

### ISSUE THREAD

**Issue by dayo05** [ivanmeler/SamFirm_Reborn#2]
Error: Could not send BinaryInform. Status code 200/400
    Request was invalid. Are you sure the input data is correct?
Could not fetch info for SHW-M250S/SKT. Please verify the input or use manual info
 
this is error message when I using this program for download Galaxy S2 Firmware
Input: 
Model: SHW-M250S
Region: SKT

**Comment by ivanmeler** [comment]
Hm interesting fw xml seems to be formated in a different way than the more recent ones, ill have to check how to fetch older fws http://fota-cloud-dn.ospserver.net/firmware/SKT/SHW-M250S/version.xml

**Comment by ivanmeler** [comment]
> SHW-M250S

After further investigation it looks like samsung removed said firmwares from their servers but it also looks like device can be coverted to international i9100 s2 https://www.youtube.com/watch?v=pXuBmhCPgdI
firmware for those can still be downloaded from samfirm and many other places
