### ISSUE TITLE
i have a dual sim j7 2015 (sm-j700h) do i need type both IMEIs in the imei/serial field and how to type both ?

### ISSUE THREAD

**Issue by no1devjdid** [ivanmeler/SamFirm_Reborn#20]
normally a dual sim device has 2 IMEIs, do i have to type both of them or only one of them ?
sorry for bad english

**Comment by ivanmeler** [comment]
You only need one imei, or you could use serial.
Best regards

**Comment by no1devjdid** [comment]
thank you very much
