### ISSUE TITLE
can't fetch for SM-G970U/SM-G970U1/SM-G970UZBATMB

### ISSUE THREAD

**Issue by dchmelik** [ivanmeler/SamFirm_Reborn#4]
I don't know if I enter SM-G970U or SM-G970U1 or SM-G970UZBATMB, and USA or US.  With all combinations, it couldn't fetch.

**Comment by ivanmeler** [comment]
Oh hey i just tried to download SM-G970U TMB fw and i had no issues doing so, tho there is a chance some carriers self host updates so they cant be downloaded with this tool, t-mobile doesnt seem to be one of those, for u1 i tested few region codes too and they worked (VZW AIO FKR)

**Comment by dchmelik** [comment]
So that's what they are, but how do I know which region code I have, also in cases devices aren't phones?

**Comment by ivanmeler** [comment]
> So that's what they are, but how do I know which region code I have, also in cases devices aren't phones?

When you put phone in download mode it should show which csc you are on (it might say sales region) you could also check it in stock recovery that method works on both phones and tablets

**Comment by dchmelik** [comment]
Didn't work but I think I found looking at information from when we bought it (TMB) but it updated to Android 12 anyway (so don't need to lookup now.)  Didn't work for different device but separate issue...

**Comment by ivanmeler** [comment]
> Didn't work but I think I found looking at information from when we bought it (TMB) but it updated to Android 12 anyway (so don't need to lookup now.) Didn't work for different device but separate issue...

you could also enter *#1234# in dialer or on devices without dialer first enter (+30,012,012,732+ in calculator and after that enter *#1234# in drparser app that shows up, it will show csc version

**Comment by dchmelik** [comment]
Thanks!  Dialer/calculator codes worked, though I may no longer need G970U firmware for possible future recovery, because, though legal to root, seems unfortunately Samsung locked bootloader... issue for other software, or trying different brand next time.  It's most likely location code is displayed in download mode, just isn't called sales region nor CSC (but same string showed  in dialer.)
