### ISSUE TITLE
Cannot download firmware for EUX/EUY CSCs of S23/S22 series

### ISSUE THREAD

**Issue by NhatHuyNguyen** [ivanmeler/SamFirm_Reborn#7]
Checking firmware for SM-S918B/EUX/S918BXXS3AWF7/S918BOXM3AWF7/S918BXXS3AWF7/S918BXXS3AWF7
Error: Could not send BinaryInform. Status code 200/400
    Request was invalid. Are you sure the input data is correct?
Could not fetch info for SM-S918B/EUX. Please verify the input or use manual info

Using manual mode yields the same error. Frija doesn't work either. Samfw website is not updating EUX/EUY firmwares.
Other new devices (like A546B, A346B) still work with EUX/EUY though.

**Comment by Garfield-Z** [comment]
Cannot download fw for S23U/S21U

Logs for S23U

SamFirm v0.3.6.4
Checking firmware for SM-S918B/SIN/S918BXXS3AWHR/S918BOXM3AWGJ/S918BXXU3AWGJ/S918BXXS3AWHR
Model: SM-S918B
Version: S918BXXS3AWHR/S918BOXM3AWGJ/S918BXXU3AWGJ/S918BXXS3AWHR
OS: T(Android 13)
Filename: SM-S918B_1_20230901100740_c8w9u534rk_fac.zip.enc4
Size: 9998368928 bytes
LogicValue: hu9hyy2l7kudw9tx


Filename: <---masked--->\SM-S918B_1_20230901100740_c8w9u534rk_fac.zip.enc4
Trying to download SM-S918B_1_20230901100740_c8w9u534rk_fac.zip.enc4 to <---masked--->\SM-S918B_1_20230901100740_c8w9u534rk_fac.zip.enc4
**Error getting response: Error downloading: 403**
Download finished

Checking CRC32...
**File for crc check not found**
System.IO.FileNotFoundException: File for crc check not found

**Comment by ivanmeler** [comment]
> Cannot download fw for S23U/S21U
> 
> Logs for S23U
> 
> SamFirm v0.3.6.4 Checking firmware for SM-S918B/SIN/S918BXXS3AWHR/S918BOXM3AWGJ/S918BXXU3AWGJ/S918BXXS3AWHR Model: SM-S918B Version: S918BXXS3AWHR/S918BOXM3AWGJ/S918BXXU3AWGJ/S918BXXS3AWHR OS: T(Android 13) Filename: SM-S918B_1_20230901100740_c8w9u534rk_fac.zip.enc4 Size: 9998368928 bytes LogicValue: hu9hyy2l7kudw9tx
> 
> Filename: <---masked--->\SM-S918B_1_20230901100740_c8w9u534rk_fac.zip.enc4 Trying to download SM-S918B_1_20230901100740_c8w9u534rk_fac.zip.enc4 to <---masked--->\SM-S918B_1_20230901100740_c8w9u534rk_fac.zip.enc4 **Error getting response: Error downloading: 403** Download finished
> 
> Checking CRC32... **File for crc check not found** System.IO.FileNotFoundException: File for crc check not found

Samsung has changed something regarding auth protocol and dropped auth v1 suppoet, im working on adding auth v2 protocol support right now and some support for downloading firmwares for wearables

**Comment by ivanmeler** [comment]
This will take some time, thanks to everyone bringing this into my attention.
On a bonus side tho it will allow us to download new regions such as EUX after migration has been done

**Comment by ivanmeler** [comment]
EUX issue still stands as its spcial firmware but since i did some research on wearable update downloads i i noticed new fw combos like EUX might use same protocol fo dl/req.

Will definetely look into this in coming weeks

**Comment by NhatHuyNguyen** [comment]
The weird part is EUX/EUY only fails for some flagship devices. I tried with an A54 and it worked normally

**Comment by ivanmeler** [comment]
Yeah i think they switched those to a same server wearables use, ill confirm in a few days because this is confusing

**Comment by Tkkg1994** [comment]
Any news on this one? Suffering from the same problem over here  :)

**Comment by QuentinSc** [comment]
👀

**Comment by corsicanu** [comment]
Imma close this as solved since 8174748ef488bbfca29cb02992c3208fb84da059 fixes the issue
