### ISSUE TITLE
Error getting response: Remote server returned error: (403) Forbidden

### ISSUE THREAD

**Issue by griha41** [ivanmeler/SamFirm_Reborn#8]
Greetings.
Application returning an error:

21.09.2023 22:55:47
SamFirm v0.3.6.4
Checking firmware for SM-A525F/XSG/A525FXXS6DWG2/A525FOJM6DWE3/A525FXXS6DWG2/A525FXXS6DWG2
Model: SM-A525F
Version: A525FXXS6DWG2/A525FOJM6DWE3/A525FXXS6DWG2/A525FXXS6DWG2
OS: T(Android 13)
Filename: SM-A525F_3_20230802162040_9rxhs70svf_fac.zip.enc4
Size: 6302423456 bytes
LogicValue: ormj4809tzho9nyj

Filename: C:\Samsung\SM-A525F\Firmware\23.09.21 [SER]\SM-A525F_3_20230802162040_9rxhs70svf_fac.zip.enc4
Trying to download SM-A525F_3_20230802162040_9rxhs70svf_fac.zip.enc4 to C:\Samsung\SM-A525F\Firmware\23.09.21 [SER]\SM-A525F_3_20230802162040_9rxhs70svf_fac.zip.enc4
Error getting response: Удаленный сервер возвратил ошибку: (403) Запрещено. [Remote server returned error: (403) Forbidden.
Error downloading: 403
Download finished
Error: File C:\Samsung\SM-A525F\Firmware\23.09.21 [SER]\SM-A525F_3_20230802162040_9rxhs70svf_fac.zip.enc4 does not exist

Irrelevant for the region: SER or XSG. Bellow listing for SM-A137F XSG Region:

Checking firmware for SM-A137F/XSG/A137FXXU3CWE1/A137FOJM3CWE1/A137FXXU3CWE1/A137FXXU3CWE1
Model: SM-A137F
Version: A137FXXU3CWE1/A137FOJM3CWE1/A137FXXU3CWE1/A137FXXU3CWE1
OS: T(Android 13)
Filename: SM-A137F_2_20230607101041_j3a0jsvvgk_fac.zip.enc4
Size: 3872806352 bytes
LogicValue: x5f0m8dak6neonks

Filename: C:\Samsung\SM-A525F\Firmware\23.09.21 [SER]\SM-A137F_2_20230607101041_j3a0jsvvgk_fac.zip.enc4
Trying to download SM-A137F_2_20230607101041_j3a0jsvvgk_fac.zip.enc4 to C:\Samsung\SM-A525F\Firmware\23.09.21 [SER]\SM-A137F_2_20230607101041_j3a0jsvvgk_fac.zip.enc4
Error getting response: Удаленный сервер возвратил ошибку: (403) Запрещено.
Error downloading: 403
Download finished
Error: File C:\Samsung\SM-A525F\Firmware\23.09.21 [SER]\SM-A137F_2_20230607101041_j3a0jsvvgk_fac.zip.enc4 does not exist

and no any problem with a folder permissions.
Idk, Is that a new Samsung bu**sh*t in 'eir heads or something?

**Comment by Garfield-Z** [comment]
Please refer to this answer from the author. 
https://github.com/ivanmeler/SamFirm_Reborn/issues/7#issuecomment-1729839685

**Comment by griha41** [comment]
Based on current experimental source release [0.3.6.5](https://github.com/ivanmeler/SamFirm_Reborn/releases/tag/0.3.6.5) I was able to download SM firmware. But you need to build it through Visual Studio (2017 / 2019 / 2022 or latest if it's exists).
Firmware size was 3608 Mb. Everything went fine! Nicely done!

**Comment by ivanmeler** [comment]
Resolved, new build has been tested and uploaded. Thanks for report
