### ISSUE TITLE
can't downlaod firmware. File for crc check not found (SM-F946N,KOO)

### ISSUE THREAD

**Issue by blossomcy1201** [ivanmeler/SamFirm_Reborn#9]
SamFirm v0.3.6.4
Checking firmware for SM-F946N/KOO/F946NKSU1AWI1/F946NOKR1AWI1/F946NKSU1AWFF/F946NKSU1AWI1
Model: SM-F946N
Version: F946NKSU1AWI1/F946NOKR1AWI1/F946NKSU1AWFF/F946NKSU1AWI1
OS: T(Android 13)
Filename: SM-F946N_1_20230907190911_h4edmdh52p_fac.zip.enc4
Size: 9376936864 bytes
LogicValue: 283bmgeh1a722oq4

Filename: C:\Users\blossom\Desktop\SM-F946N_1_20230907190911_h4edmdh52p_fac.zip.enc4
Trying to download SM-F946N_1_20230907190911_h4edmdh52p_fac.zip.enc4 to C:\Users\blossom\Desktop\SM-F946N_1_20230907190911_h4edmdh52p_fac.zip.enc4
Error getting response: 원격 서버에서 (403) 사용할 수 없음 오류를 반환했습니다.
Error downloading: 403
Download finished

Checking CRC32...
File for crc check not found
System.IO.FileNotFoundException: File for crc check not found
   위치: SamFirm.Utility.CRCCheck(String file, Byte[] crc) 파일 C:\Users\i_iva\Desktop\SamFirm_Reborn\Utility.cs:줄 94
   위치: SamFirm.Form1.<download_button_Click>b__44_0(Object o, DoWorkEventArgs _e) 파일 C:\Users\i_iva\Desktop\SamFirm_Reborn\Form1.cs:줄 225

same as SM-G525N, KOO and any other devices and CSC has same issue... Caused by samsung?

**Comment by Garfield-Z** [comment]
Please refer to this answer from the author. 
https://github.com/ivanmeler/SamFirm_Reborn/issues/7#issuecomment-1729839685

**Comment by blossomcy1201** [comment]
thks you bro. I will check comment.

**Comment by ivanmeler** [comment]
Resolved with latest release, thanks for bringing it into attention
